spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600
            exposedHeaders:
              - "Authorization"
              - "Content-Type"

jwt:
  secret: ${JWT_SECRET:SYDLF52DangerKeySYDLF9911894325962389476582937465986348957632897562387ww7sfusdfy9374hguif738794fgu9iw3g4f987uswuhfiuGIUDS9GDUSWHTPIWEHYS0DFS098DF98SDFSHDFUSH9374FISDU87SADASUDGHGHAISD7A9OSD823UGHRUIHGSDW9D78Y238RUIOSWADHFOUWHSSDFDDUHWWF9384FGSD}

auth-service:
  url: http://${AUTH_SERVICE_HOST:auth-service}:${AUTH_SERVICE_PORT:8081}

user-service:
  url: http://${CORE_API_HOST:core-api-service}:${CORE_API_PORT:8082}

chat-service:
  url: http://${CORE_API_HOST:core-api-service}:${CORE_API_PORT:8082}

message-service:
  url: http://${CORE_API_HOST:core-api-service}:${CORE_API_PORT:8082}

websocket-server:
  url: ws://${WS_SERVICE_HOST:websocket-server}:${WS_SERVICE_PORT:8092}

