spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    consumer:
      bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}

jwt:
  secret: ${JWT_SECRET:SYDLF52DangerKeySYDLF9911894325962389476582937465986348957632897562387ww7sfusdfy9374hguif738794fgu9iw3g4f987uswuhfiuGIUDS9GDUSWHTPIWEHYS0DFS098DF98SDFSHDFUSH9374FISDU87SADASUDGHGHAISD7A9OSD823UGHRUIHGSDW9D78Y238RUIOSWADHFOUWHSSDFDDUHWWF9384FGSD}

websocket:
  port: 8092
  allowed-origins: "*"
  heartbeat-interval: 30000
